-- ################################################
-- 			Data Analysis of Aerospace data
-- ################################################


-- 1. query to see data in airlines table
select * from airlines limit 10;


-- 2. query to see in part_sales table
select * from part_sales limit 10;


-- 3. query to see in parts table
select * from parts limit 10;


-- 4. Total Revenue generated across all parts
select round(sum(revenue),2) as total_revenue from part_sales;


-- 5. Total quantity of parts sold
select count(*) as part_quantity from part_sales;


-- 6. Airline wise total revenue
select airline, sum(revenue) as total_revenue from part_sales group by airline order by total_revenue desc;


-- 7. Part wise total revenue
select part_id, sum(revenue) as total_revenue from part_sales group by part_id order by total_revenue desc;


-- 8. Part Category wise total revenue
select part_category, sum(revenue) as total_revenue from part_sales group by part_category order by total_revenue desc;


-- 9. Part Category wise Average Selling Price (Revenue/Quantity)
select part_category, sum(revenue)/sum(quantity) as asp from part_sales group by part_category order by asp desc;


-- 10. Monthly Revenue Trend
select date_trunc('month', order_date) as month, sum(revenue) from part_sales group by date_trunc('month', order_date) order by month;


-- 11. Month with Highest Revenue
select date_trunc('month', order_date) as month, sum(revenue) as total_revenue from part_sales group by month order by total_revenue desc limit 1;


-- 12. Revenue share of each airline 
select airline, round(100*sum(revenue)/ (select sum(revenue) from part_sales),2) as pct_share from part_sales group by airline order by pct_share desc;

-- 13. Month over Month (MoM) Revenue
-- CTE for monthly revenue
with monthly_revenue as (
select date_trunc('month', order_date) as month, sum(revenue) as revenue
from part_sales 
group by month
order by month
)

select month, revenue, lag(revenue) over(order by month) as previous_revenue, 
round(100*(revenue- lag(revenue) over(order by month))/nullif(lag(revenue) over(order by month),0),2)
as revenue_growth_pct from monthly_revenue


-- 14. Week Over Week (WoW) Revenue
-- CTE for weekly revenue
with weekly_revenue as (
select date_trunc('week', order_date) as week, sum(revenue) as revenue
from part_sales 
group by week
order by week
)

select week, revenue, lag(revenue) over(order by week) as previous_revenue, 
round(100*(revenue- lag(revenue) over(order by week))/nullif(lag(revenue) over(order by week),0),2) 
as revenue_growth_pct from weekly_revenue


-- 15. Running Revenue per order_date

select order_date, revenue, sum(revenue) over (order by order_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as running_revenue from part_sales order by order_date;


-- 16. Running Revenue per airline (try to understand this)

select airline, sum(revenue), sum(revenue) over(order by airline)  as running_revenue from part_sales group by airline;



-- Region wise revenue in descending order
-- Insight --> Europe generated maximum revenue out all regions indicating strong demand of airlines

select a.region, sum(ps.revenue) as total_revenue
from part_sales as ps
join airlines a 
on ps.airline = a.airline
group by a.region
order by total_revenue desc;


-- Country wise revenue in descending order

select a.country, sum(ps.revenue) as total_revenue
from part_sales as ps
join airlines a
on ps.airline = a.airline 
group by a.country 
order by total_revenue desc;

-- Total number of parts supplied by manufacturer and their respective price

select manufacturer, count(part_id) as part_count, sum(base_price_usd) as total_price
from parts group by manufacturer;


-- Total Revenue generated by each Manufacturer
-- Insight -> Safran generated maximum revenue followed by Thales and GE Aerospace
select p.manufacturer, sum(p.base_price_usd) as total_price,sum(ps.revenue) as total_revenue, 
sum(ps.revenue) - sum(p.base_price_usd) as revenue_vs_base_price
from part_sales as ps
join parts as p
on ps.part_id = p.part_id
group by p.manufacturer
order by total_revenue desc;

-- Revenue generated by manufacturer in each region by revenue
select a.region, p.manufacturer,sum(ps.revenue) as total_revenue,
rank() over(partition by A.REGION order by sum(ps.revenue) desc) as rnk
from airlines as a
join part_sales ps 
on a.airline = ps.airline
join parts as p
on ps.part_id = p.part_id
group by a.region, p.manufacturer
order by a.region;

-- Top manufacturer which generated maximum revenue in each region

with temp_table as (
select a.region as region, p.manufacturer as manufacturer ,sum(ps.revenue) as total_revenue,
rank() over(partition by A.REGION order by sum(ps.revenue) desc) as rnk
from airlines as a
join part_sales ps 
on a.airline = ps.airline
join parts as p
on ps.part_id = p.part_id
group by a.region, p.manufacturer
order by a.region
)

select region, manufacturer, total_revenue
from temp_table 
where rnk =1;

-- Top selling part each month
select 
date_trunc('month', order_date) as month,
part_id,
sum(revenue) as total_revenue,
rank() over(partition by date_trunc('month', order_date) order by sum(revenue) desc) as rnk
from part_sales
group by date_trunc('month', order_date), part_id
order by month;

-- top 2 airline by revenue in each country

select country, airline, sum(revenue), dense_rank() over(partition by country order by sum(revenue) desc) as rnk
from part_sales
group by country, airline
order by country, rnk;

-- Manufacturer above average revenue

with manufacturer_revenue as (
select p.manufacturer, sum(ps.revenue) as total_revenue
from parts as p join part_sales as ps
on p.part_id = ps.part_id
group by p.manufacturer

)

select * from manufacturer_revenue
where total_revenue > (select avg(total_revenue) from manufacturer_revenue) 
























